# Generated by Django 6.1 on 2026-09-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_created_at_alter_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
